version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: src/TimeTracker.Api/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - timetracker-network

  client:
    build:
      context: .
      dockerfile: src/TimeTracker.Client/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - api
    networks:
      - timetracker-network

networks:
  timetracker-network:
    driver: bridge 